/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface StencilSlots {}
  interface StencilSlotsAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'StencilSlots': Components.StencilSlots;
  }

  interface StencilIntrinsicElements {
    'stencil-slots': Components.StencilSlotsAttributes;
  }


  interface HTMLStencilSlotsElement extends Components.StencilSlots, HTMLStencilElement {}
  var HTMLStencilSlotsElement: {
    prototype: HTMLStencilSlotsElement;
    new (): HTMLStencilSlotsElement;
  };

  interface HTMLElementTagNameMap {
    'stencil-slots': HTMLStencilSlotsElement
  }

  interface ElementTagNameMap {
    'stencil-slots': HTMLStencilSlotsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
